name: Commit Checks
on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  Pull-Request-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test --if-present
      - run: npm run pretty-check --if-present